data:
  train_index: "data/train_index.txt"  # Update after data prep
model:
  latent_dim: 128
training:
  batch_size: 8
  lr: 1e-4
  kl_weight: 0.001
  epochs: 100
  ckpt_dir: "checkpoints/"
  prior_lr: 1e-4
  prior_epochs: 100
inference:
  sample_rate: 48000
